### ISSUE TITLE
Nov 21 Google Outage

### ISSUE THREAD

**Issue by steve4650** [queer/outage.bingo#5]
I think `Google (main servers)` should be checked for Nov 21!

https://indianexpress.com/article/technology/tech-news-technology/gmail-google-calendar-google-chat-reported-outages-a-cross-europe-asia-and-us-7619761/

**Comment by queer** [comment]
Good catch, thank you :D

**Comment by queer** [comment]
Added in https://github.com/queer/outage.bingo/commit/f2df483ebba744e59f87cdc60ab76817ae9bbb12
